# Generated by Django 2.1.5 on 2019-01-29 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="quantumcats",
            old_name="catchoices",
            new_name="cat_choices",
        ),
    ]
